on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.9.4'

      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Compile project
        run: mix compile

      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: _build
          path: _build/

      - name: Upload dependencies
        uses: actions/upload-artifact@v1
        with:
          name: deps
          path: deps
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'cambiatus_test'
          postgresql user: 'postgres'
          postgresql password: '123123123'

      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: _build

      - name: Download dependencies
        uses: actions/download-artifact@v1
        with:
          name: deps

      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.9.4'

      - name: Run all tests
        run: mix test
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: _build

      - name: Download dependencies
        uses: actions/download-artifact@v1
        with:
          name: deps

      - uses: actions/setup-elixir@v1
        with:
          otp-version: '22.2'
          elixir-version: '1.9.4'

      - name: Lint project
        run: mix credo
